### ISSUE TITLE
Current OpenWrap release not installable

### ISSUE THREAD

**Issue by scottlittlewood** [OpenWrap/openwrap#115]
I cleaned out the previous version of OpenWrap from my local directory: C:\Documents and Settings\scott.littlewood\Local Settings\Application Data\openwrap\

Upon downloading and running o.exe again I get the following 2 error messages:

C:\openwrap>o
The OpenWrap shell is not installed on this machine. Do you want to:
(i) install the shell and make it available on the path?
(c) use the current executable location and make it available on the path?
(n) do nothing?
c
OpenWrap bootstrapping failed.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Documents and Settings\scott.littlewood\Local Settings\Application Data\openwrap\o.exe.link'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secA
ttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at OpenWrap.BootstrapRunner.InstallLinkToCurrentVersion()
   at OpenWrap.BootstrapRunner.InstallFreshVersion()
   at OpenWrap.BootstrapRunner.VerifyConsoleInstalled()
   at OpenWrap.BootstrapRunner.Run(String[] args)

C:\openwrap>o
The OpenWrap shell is not installed on this machine. Do you want to:
(i) install the shell and make it available on the path?
(c) use the current executable location and make it available on the path?
(n) do nothing?
i
Installing the shell to 'C:\Documents and Settings\scott.littlewood\Local Settings\Application Data\openwrap'.
Downloading http://wraps.openwrap.org/index.wraplist [....................]
Downloading http://wraps.openwrap.org/openwrap-1.0.0.22362252.wrap [.............]
Downloading http://wraps.openwrap.org/openfilesystem-1.0.0.19074013.wrap [..............]
Downloading http://wraps.openwrap.org/sharpziplib-0.85.5.452.wrap [.............]
# OpenWrap v1.0.0.0 ['C:\Documents and Settings\scott.littlewood\Local Settings\Application Data\openwrap\wraps_cache\openwrap-1.0.0.22362252\bin-net35\OpenWrap.dll']

No command was entered. Type 'get-help' to get a list of supported commands.
OpenWrap could not be started.
Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'OpenWrap.Services.Serv
ices' threw an exception. ---> System.TypeLoadException: Could not load type 'OpenFileSystem.IO.Path' from assembly 'OpenFileSystem, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at OpenWrap.Services.PackageDescriptorMonitor..ctor()
   at OpenWrap.Services.Services.Clear() in c:\src\openwrap\src\OpenWrap\Services\Services.cs:line 40
   at OpenWrap.Services.Services..cctor() in c:\src\openwrap\src\OpenWrap\Services\Services.cs:line 12
   --- End of inner exception stack trace ---
   at OpenWrap.Services.Services.RegisterService[TService](TService instance)
   at OpenWrap.ConsoleRunner.Main(String[] args) in c:\src\openwrap\src\OpenWrap\ConsoleRunner.cs:line 34
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.RuntimeMethodHandle.InvokeMethodFast(Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenWrap.BootstrapRunner.ExecuteEntryPoint(String[] args, Assembly entryPointAssembly)
   at OpenWrap.BootstrapRunner.Run(String[] args)

C:\openwrap>

**Comment by serialseb** [comment]
Outdated OFS package. Now updated to latest version (1.0.0.21942093)
