### ISSUE TITLE
Running from bash inside of cygwin mintty fails when reading input from console

### ISSUE THREAD

**Issue by petemounce** [OpenWrap/openwrap#196]
- Download o.exe
- Open bash shell (inside cygwin's mintty)
- Run ./o.exe
- Observe exception

I guess a non-Windows shell is a fairly rare use-case...?

``` shell
~/profile/Downloads
$ ./o.exe i
The OpenWrap shell is not installed on this machine. Do you want to:
(i) install the shell and make it available on the path?
(c) use the current executable location and make it available on the path?
(n) do nothing?
OpenWrap bootstrapping failed.
System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at System.Console.ReadKey()
   at OpenWrap.ConsoleNotifier.InstallOptions()
   at OpenWrap.BootstrapRunner.InstallFreshVersion()
   at OpenWrap.BootstrapRunner.Run(String[] args)
```

**Comment by serialseb** [comment]
Replicated on https://github.com/openrasta/openwrap-bootstrap/issues/17 and closed, as this is a shell issue.

You can solve the problem by writing an o.sh or equivalent in your path that wraps o and passes the -shellinstall parameter (see shell documentation on the wiki)
