### ISSUE TITLE
System.InvalidOperationException: Sequence contains more than one element

### ISSUE THREAD

**Issue by jonnyzzz** [OpenWrap/openwrap#240]
```
# OpenWrap Shell 1.1.0.35
# Copyright c naughtyProd Limited 2009-2011
# Using C:\Users\jonnyzzz\AppData\Local\openwrap\wraps\_cache\openwrap-2.0.0.81133579\bin-net35\OpenWrap.dll (2.0.0.0)

# OpenWrap Shell could not start.

Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at OpenWrap.Commands.Cli.Locators.NamedCommandLocator.FindCommand(String verbNounToken) in c:\src\openwrap\src\OpenWrap\Commands\Cli\Locators\NamedCommandLocator.cs:line 20
   at OpenWrap.Commands.Cli.Locators.VerbNounCommandLocator.Execute(String& input) in c:\src\openwrap\src\OpenWrap\Commands\Cli\Locators\VerbNounCommandLocator.cs:line 18
   at OpenWrap.Commands.Cli.ConsoleCommandExecutor.<>c__DisplayClass4.<Execute>b__1(ICommandLocator x) in c:\src\openwrap\src\OpenWrap\Commands\Cli\ConsoleCommandExecutor.cs:line 27
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at OpenWrap.Commands.Cli.ConsoleCommandExecutor.Execute(String commandLine, IEnumerable`1 optionalInputs) in c:\src\openwrap\src\OpenWrap\Commands\Cli\ConsoleCommandExecutor.cs:line 27
   at OpenWrap.Commands.Cli.ShellRunner.Main(IDictionary`2 env) in c:\src\openwrap\src\OpenWrap\Commands\Cli\ShellRunner.cs:line 55
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenWrap.BootstrapRunner.<>c__DisplayClass16.<LoadEntrypointCache>b__15(IDictionary`2 env)
   at OpenWrap.BootstrapRunner.ExecuteEntrypoint(KeyValuePair`2 entryPoint, IEnumerable`1 assemblies, IEnumerable`1 consumedArgs)
   at OpenWrap.BootstrapRunner.Run(String[] args)
```

**Comment by serialseb** [comment]
Can you try updating to the lastest shell (http://github.com/OpenWrap/openwrap.github.com/raw/master/o.exe) and retry?

**Comment by serialseb** [comment]
Fixed

**Comment by serialseb** [comment]
Actually not fixed, that's another issue alltogether.

**Comment by rvdginste** [comment]
From what I see, this just looks like the error you get when you do not completely specify the command you are trying to execute.... for example the following: o l-w

This could mean either "lock-wrap" or "list-wrap"... it's a pity jonnyzzz didn't also mention the commandline he used....

**Comment by jonnyzzz** [comment]
I've been playing with openwrap command with deleted wraps folder for the solution. I do not remember the command I tried.
