### ISSUE TITLE
OpenWrap2 and Resharper6

### ISSUE THREAD

**Issue by leesmith110** [OpenWrap/openwrap#248]
Details from output window...  It not resolving the resharper references, one of the component projects does, but this solution doesnt.

OpenWrap Visual Studio Integration (2.0.0.0) starting.
Root location: C:\Development\NICE\evidence
Loading packages...
Loading package C:\Development\NICE\evidence\wraps_cache\openwrap-2.0.0.81396426
Loading package C:\Development\NICE\evidence\wraps_cache\SharpZipLib-0.86.0
Loading package C:\Development\NICE\evidence\wraps_cache\openfilesystem-1.0.0.61263243
Loading package C:\Development\NICE\evidence\wraps_cache\tdnet-framework-2.0.0.48555719
Loading package C:\Development\NICE\evidence\wraps_cache\Mono.Cecil-0.9.4.1
Solution plugins starting...
Starting plugin AssemblyReferenceNotificationsPlugin.
Plugin initialization failed.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, Boolean& pfNeedsRelease)
   at System.Runtime.InteropServices.UCOMIConnectionPoint.Advise(Object pUnkSink, Int32& pdwCookie)
   at EnvDTE._dispSolutionEvents_EventProvider.add_ProjectRemoved(_dispSolutionEvents_ProjectRemovedEventHandler A_1)
   at EnvDTE.SolutionEventsClass.add_ProjectRemoved(_dispSolutionEvents_ProjectRemovedEventHandler A_1)
   at OpenWrap.VisualStudio.ProjectModel.DteSolution..ctor(Solution solution) in c:\src\openwrap\src\OpenWrap.VisualStudio.Shared\ProjectModel\DteSolution.cs:line 24
   at OpenWrap.SolutionPlugins.VisualStudio.AssemblyReferenceNotificationsPlugin..ctor() in c:\src\openwrap\src\OpenWrap.VisualStudio.SolutionPlugins\AssemblyReferenceNotificationsPlugin.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipVisibilityChecks, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName)
   at OpenWrap.PackageManagement.Exporters.SolutionPlugin.Start() in c:\src\openwrap\src\OpenWrap\PackageManagement\Exporters\SolutionPlugin.cs:line 30
   at OpenWrap.Commands.Core.StartSolutionPlugin.<>c__DisplayClass23.<LoadPlugin>b__21() in c:\src\openwrap\src\OpenWrap.Commands\Core\StartSolutionPlugin.cs:line 109
   at OpenWrap.Commands.Core.StartSolutionPlugin.TryDo(Action action, Action`1 onError) in c:\src\openwrap\src\OpenWrap.Commands\Core\StartSolutionPlugin.cs:line 133
Starting plugin ReSharperLoaderPlugin.
Resharper Plugin Manager: Loaded (2.0.0.329).
ReSharper Project Reference Updater: Solution opened NHS.Evidence.Tagging
All solution plugins started.
ReSharper test runner starting.

**Comment by serialseb** [comment]
That's fixed in a9c18a00b64b5a71915d9e7ea81cb7984140afeb
