### ISSUE TITLE
-SystemRepositoryPath is broken

### ISSUE THREAD

**Issue by TripleEmcoder** [OpenWrap/openwrap#273]
I'm trying to use o.exe in a sandboxem environment (unit test), but it keeps failing on me with the -SystemRepositoryPath flag. On first run it downloads all packages like on install, but then fails to execute any command. Packages seem to be stored on disk correctly. Here's the stack trace:

```
> o.exe -SystemRepositoryPath E:\Test\Temp -ShellInstall None

# OpenWrap Shell 2.0.0.10
# Copyright c naughtyProd Limited 2009-2011
# Using E:\Test\Temp\wraps\_cache\openwrap-1.0.2.86964541\bin-net35\OpenWrap.dll (1.0.0.0)

# OpenWrap Shell could not start.

Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenWrap.Commands.NounNotFound..ctor(IEnumerable`1 nouns) in c:\src\openwrap\src\OpenWrap\Commands\NounNotFound.cs:line 22
   at OpenWrap.Commands.Cli.CommandLineProcessor.<Execute>d__32.MoveNext() in c:\src\openwrap\src\OpenWrap\Commands\Cli\CommandLineProcessor.cs:line 35
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at OpenWrap.Commands.Cli.CliConsoleRunner.Main(String[] args) in c:\src\openwrap\src\OpenWrap\Commands\Cli\CliConsoleRunner.cs:line 50
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OpenWrap.BootstrapRunner.<>c__DisplayClass40.<FindLegacyEntrypoint>b__37(String[] args)
   at OpenWrap.BootstrapRunner.ExecuteEntrypoint(String[] args, KeyValuePair`2 entryPoint)
   at OpenWrap.BootstrapRunner.Run(String[] args)
```

**Comment by serialseb** [comment]
Closed in openrasta/openwrap-shell@f2469c13b105353848300b063b9a6c7b3d584aec
