### ISSUE TITLE
Proxy Authentication Required

### ISSUE THREAD

**Issue by ol3j** [OpenWrap/openwrap#277]
Hi, 

I have  problem I need  user name and pass when o connects with the repository or change proxy.

Downloading http://wraps.openwrap.org/index.wraplist [
Unhandled Exception: System.Net.WebException: The remote server returned an erro
r: (407) Proxy Authentication Required.
   at OpenWrap.Preloading.NotifyProgressWebClient.DownloadDataCompleted(Object s
ender, DownloadDataCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadDataCompleted(DownloadDataCompletedEventArg
s e)
   at System.Net.WebClient.DownloadDataOperationCompleted(Object arg)
   at System.Threading._ThreadPoolWaitCallback.WaitCallback_Context(Object state
)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallbackInternal(_Thre
adPoolWaitCallback tpWaitCallBack)
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback(Object state)

]

**Comment by serialseb** [comment]
See https://github.com/openrasta/openwrap/wiki/OpenWrap-Shell you can use -proxyhref, -proxyusername and -proxypassword. If the proxy is correctly configured in the internet options this ought to work out of the box without configuration.

**Comment by serialseb** [comment]
Marking as won't fix as no answer. if you still have issues can you reopen this bug please.
