### ISSUE TITLE
build/test.bat fails

### ISSUE THREAD

**Issue by haf** [OpenWrap/openwrap#296]
When trying to build with `build/test.bat`, it fails, w/ this output:

```
D:\code\oss\openwrap\build>copy /Y ..\scratch\bin\OpenWrap-Debug-AnyCPU\*.* ..\wraps\openwrap\bin-net35
..\scratch\bin\OpenWrap-Debug-AnyCPU\ICSharpCode.SharpZipLib.dll
..\scratch\bin\OpenWrap-Debug-AnyCPU\Mono.Cecil.dll
..\scratch\bin\OpenWrap-Debug-AnyCPU\Mono.Cecil.Mdb.dll
..\scratch\bin\OpenWrap-Debug-AnyCPU\Mono.Cecil.Pdb.dll
..\scratch\bin\OpenWrap-Debug-AnyCPU\Mono.Cecil.Rocks.dll
..\scratch\bin\OpenWrap-Debug-AnyCPU\Mono.Posix.dll
..\scratch\bin\OpenWrap-Debug-AnyCPU\OpenFileSystem.dll
..\scratch\bin\OpenWrap-Debug-AnyCPU\OpenFileSystem.pdb
..\scratch\bin\OpenWrap-Debug-AnyCPU\OpenRasta.Client.dll
..\scratch\bin\OpenWrap-Debug-AnyCPU\OpenRasta.Client.pdb
..\scratch\bin\OpenWrap-Debug-AnyCPU\OpenWrap.dll
..\scratch\bin\OpenWrap-Debug-AnyCPU\OpenWrap.pdb
..\scratch\bin\OpenWrap-Debug-AnyCPU\TestDriven.Framework.dll
       13 file(s) copied.

D:\code\oss\openwrap\build>copy /Y ..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\*.* ..\wraps\openwrap\build
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\ICSharpCode.SharpZipLib.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\Mono.Cecil.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\Mono.Cecil.Mdb.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\Mono.Cecil.Pdb.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\Mono.Cecil.Rocks.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\Mono.Posix.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenFileSystem.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenFileSystem.pdb
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Build.Bootstrap.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Build.Bootstrap.pdb
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Build.Tasks.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Build.Tasks.pdb
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.CSharp.targets
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.pdb
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Resharper.450.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Resharper.450.pdb
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Resharper.500.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Resharper.500.pdb
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Resharper.510.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Resharper.510.pdb
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Resharper.511.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.Resharper.511.pdb
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.tasks
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.VisualStudio.ComShim.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.VisualStudio.ComShim.pdb
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.VisualStudio.dll
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\OpenWrap.VisualStudio.pdb
..\scratch\bin\OpenWrap.Build.Tasks-Debug-AnyCPU\TestDriven.Framework.dll
       29 file(s) copied.

D:\code\oss\openwrap\build>copy /Y ..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\*.* ..\wraps\openwrap\commands
..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\ICSharpCode.SharpZipLib.dll
..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\Mono.Cecil.dll
..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\Mono.Cecil.Mdb.dll
..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\Mono.Cecil.Pdb.dll
..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\Mono.Cecil.Rocks.dll
..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\Mono.Posix.dll
..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\OpenFileSystem.dll
..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\OpenFileSystem.pdb
..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\OpenWrap.Commands.dll
..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\OpenWrap.Commands.pdb
..\scratch\bin\OpenWrap.Commands-Debug-AnyCPU\TestDriven.Framework.dll
        1 file(s) copied.

D:\code\oss\openwrap\build>pause
Press any key to continue . . .

D:\code\oss\openwrap\build>msbuild self-build.test
Microsoft (R) Build Engine Version 4.0.30319.1
[Microsoft .NET Framework, Version 4.0.30319.239]
Copyright (C) Microsoft Corporation 2007. All rights reserved.

Build started 2012-01-10 13:27:47.
Project "D:\code\oss\openwrap\build\self-build.test" on node 1 (default targets).
Project "D:\code\oss\openwrap\build\self-build.test" (1) is building "D:\code\oss\openwrap\build\openwrap.proj" (2) on
node 1 (Clean target(s)).
Clean:
  Directory "D:\code\oss\openwrap\build\..\scratch\build" doesn't exist. Skipping.
  Directory "D:\code\oss\openwrap\build\..\scratch\package" doesn't exist. Skipping.
Done Building Project "D:\code\oss\openwrap\build\openwrap.proj" (Clean target(s)).

RemoveTemporaryPackages:
  Cleaning OpenWrap results
  Directory "D:\code\oss\openwrap\build\..\wraps\_cache\openwrap-42.0.0.1" doesn't exist. Skipping.
  Directory "D:\code\oss\openwrap\build\..\wraps\_cache\openwrap-42.0.0.0" doesn't exist. Skipping.
OpenWrap-SelfBuild:
  Building OpenWrap from existing dependencies.
Project "D:\code\oss\openwrap\build\self-build.test" (1) is building "D:\code\oss\openwrap\build\openwrap.proj" (2:2) o
n node 1 (default targets).
Clean:
  Directory "D:\code\oss\openwrap\build\..\scratch\build" doesn't exist. Skipping.
  Directory "D:\code\oss\openwrap\build\..\scratch\package" doesn't exist. Skipping.
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018: The "InitializeOpenWrap" task failed unexpectedly.\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018: System.Reflection.TargetInvocationException: Exception h
as been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018: Parameter name: path\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.IO.DirectoryInfo..ctor(String path)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenFileSystem.IO.FileSystems.Local.LocalDirectory
..ctor(String directoryPath) in c:\TeamCity\buildAgent\work\c71e0c1ab1563c43\src\OpenFileSystem\FileSystems\Local\Local
Directory.cs:line 18\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenFileSystem.IO.FileSystems.Local.Win32.Win32Dir
ectory..ctor(String directoryPath) in c:\TeamCity\buildAgent\work\c71e0c1ab1563c43\src\OpenFileSystem\FileSystems\Local
\Win32\Win32Directory.cs:line 11\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenFileSystem.IO.FileSystems.Local.Win32.Win32Fil
eSystem.GetDirectory(String directoryPath) in c:\TeamCity\buildAgent\work\c71e0c1ab1563c43\src\OpenFileSystem\FileSyste
ms\Local\Win32\Win32FileSystem.cs:line 10\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Build.MSBuildEnvironment..ctor(String pro
jectFileDirectory, String currentDirectory) in c:\src\openwrap\src\OpenWrap\Build\MSBuildEnvironment.cs:line 9\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Build.BuildInitializer.<>c__DisplayClass2
.<Initialize>b__1() in c:\src\openwrap\src\OpenWrap\Build\BuildInitializer.cs:line 18\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.<>c__DisplayClass
2`1.<TryRegisterService>b__0() in c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 60\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.Instantiate[T]()
in c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 36\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.GetService[T]() i
n c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 27\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceRegistry.<.ctor>b__15() i
n c:\src\openwrap\src\OpenWrap\Services\ServiceRegistry.cs:line 97\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.<>c__DisplayClass
2`1.<TryRegisterService>b__0() in c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 60\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.Instantiate[T]()
in c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 36\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.GetService[T]() i
n c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 27\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceRegistry.Initialize() in
c:\src\openwrap\src\OpenWrap\Services\ServiceRegistry.cs:line 118\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Build.BuildInitializer.Initialize(String
projectFile, String currentDirectory) in c:\src\openwrap\src\OpenWrap\Build\BuildInitializer.cs:line 17\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    --- End of inner exception stack trace ---\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.RuntimeMethodHandle._InvokeMethodFast(IRunt
imeMethodInfo method, Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, Runti
meType typeOwner)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.RuntimeMethodHandle.InvokeMethodFast(IRunti
meMethodInfo method, Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeType t
ypeOwner)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.Reflection.RuntimeMethodInfo.Invoke(Object
obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.Reflection.RuntimeMethodInfo.Invoke(Object
obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.Reflection.MethodBase.Invoke(Object obj, Ob
ject[] parameters)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Build.InitializeOpenWrap.Execute() in F:\
code\oss\openwrap\src\OpenWrap.Build.Bootstrap\InitializeOpenWrap.cs:line 41\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsof
t.Build.BackEnd.ITaskExecutionHost.Execute()\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstant
iatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bu
cket, TaskExecutionMode howToExecuteTask, Boolean& taskResult)
Done Building Project "D:\code\oss\openwrap\build\openwrap.proj" (default targets) -- FAILED.

Done Building Project "D:\code\oss\openwrap\build\self-build.test" (default targets) -- FAILED.


Build FAILED.

"D:\code\oss\openwrap\build\self-build.test" (default target) (1) ->
"D:\code\oss\openwrap\build\openwrap.proj" (default target) (2:2) ->
(_Initialize target) ->
  D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018: The "InitializeOpenWrap" task failed unexpectedly.\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018: System.Reflection.TargetInvocationException: Exception h
as been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018: Parameter name: path\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.IO.DirectoryInfo..ctor(String path)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenFileSystem.IO.FileSystems.Local.LocalDirectory
..ctor(String directoryPath) in c:\TeamCity\buildAgent\work\c71e0c1ab1563c43\src\OpenFileSystem\FileSystems\Local\Local
Directory.cs:line 18\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenFileSystem.IO.FileSystems.Local.Win32.Win32Dir
ectory..ctor(String directoryPath) in c:\TeamCity\buildAgent\work\c71e0c1ab1563c43\src\OpenFileSystem\FileSystems\Local
\Win32\Win32Directory.cs:line 11\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenFileSystem.IO.FileSystems.Local.Win32.Win32Fil
eSystem.GetDirectory(String directoryPath) in c:\TeamCity\buildAgent\work\c71e0c1ab1563c43\src\OpenFileSystem\FileSyste
ms\Local\Win32\Win32FileSystem.cs:line 10\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Build.MSBuildEnvironment..ctor(String pro
jectFileDirectory, String currentDirectory) in c:\src\openwrap\src\OpenWrap\Build\MSBuildEnvironment.cs:line 9\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Build.BuildInitializer.<>c__DisplayClass2
.<Initialize>b__1() in c:\src\openwrap\src\OpenWrap\Build\BuildInitializer.cs:line 18\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.<>c__DisplayClass
2`1.<TryRegisterService>b__0() in c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 60\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.Instantiate[T]()
in c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 36\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.GetService[T]() i
n c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 27\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceRegistry.<.ctor>b__15() i
n c:\src\openwrap\src\OpenWrap\Services\ServiceRegistry.cs:line 97\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.<>c__DisplayClass
2`1.<TryRegisterService>b__0() in c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 60\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.Instantiate[T]()
in c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 36\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceLocator.GetService[T]() i
n c:\src\openwrap\src\OpenWrap\Services\ServiceLocator.cs:line 27\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Services.ServiceRegistry.Initialize() in
c:\src\openwrap\src\OpenWrap\Services\ServiceRegistry.cs:line 118\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Build.BuildInitializer.Initialize(String
projectFile, String currentDirectory) in c:\src\openwrap\src\OpenWrap\Build\BuildInitializer.cs:line 17\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    --- End of inner exception stack trace ---\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.RuntimeMethodHandle._InvokeMethodFast(IRunt
imeMethodInfo method, Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, Runti
meType typeOwner)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.RuntimeMethodHandle.InvokeMethodFast(IRunti
meMethodInfo method, Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeType t
ypeOwner)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.Reflection.RuntimeMethodInfo.Invoke(Object
obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.Reflection.RuntimeMethodInfo.Invoke(Object
obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at System.Reflection.MethodBase.Invoke(Object obj, Ob
ject[] parameters)\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at OpenWrap.Build.InitializeOpenWrap.Execute() in F:\
code\oss\openwrap\src\OpenWrap.Build.Bootstrap\InitializeOpenWrap.cs:line 41\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsof
t.Build.BackEnd.ITaskExecutionHost.Execute()\r
D:\code\oss\openwrap\build\openwrap.proj(21,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstant
iatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bu
cket, TaskExecutionMode howToExecuteTask, Boolean& taskResult)
```

**Comment by serialseb** [comment]
test.bat is very very outdated, should be removed from the source code.

**Comment by haf** [comment]
Ah, well then. This this issue = that ;)

**Comment by serialseb** [comment]
Been removed in dev branches, closing.
