### ISSUE TITLE
Querying nuget remote repo potentially never terminates

### ISSUE THREAD

**Issue by haf** [OpenWrap/openwrap#300]
Trying to get started with some publishing of wraps, figured I'd do ours first. So I need to query them, to convert them:

`o list-wrap -remote nuget -query castle.core`

```
PS D:\code\oss> o list-wrap -remote nuget -query castle.core
# OpenWrap Shell 2.0.0.10
# Copyright © naughtyProd Limited 2009-2011
# Using C:\Users\xyz\AppData\Local\openwrap\wraps\_cache\openwrap-2.0.2.87978029\bin-net35\OpenWrap.dll (2.0.0.1)
```

This doesn't seem to return for me so far. At least it takes too long. I've been waiting six minutes now.

**Comment by serialseb** [comment]
Known issue till the feed cache is in place

## 

Sebastien Lambla

**Comment by haf** [comment]
I remember I had this problem 6-9 months ago also. It's pretty much a show-stopper for me, actually. Could you point me to the pipeline where I could add a cache?

**Comment by haf** [comment]
Hmm, forgot that o build-wrap had cached something in the wraps/cache folder, and of course `git clean -fxd` removed that cache......

**Comment by serialseb** [comment]
No the code is not available at this time unfortunately and won't have time till the weekend to sanitize it and push it out.

There's a couple of other changes to the nuget support that are going to land this weekend. In the meantime, i'd recommend adding the packages to your system repo or a remote you create as proxy and use that until the cache has landed. If you want to contribute to that code, you'll be able to from this WE

##

**Comment by haf** [comment]
I must have borked my installation: can't get it back to normal, even after re-installing o.exe with itself after deleting the openwrap folder... _sigh_

```
PS D:\code\oss\openwrap> o build-wrap -release -path C:\Users\xyz\AppData\Local\openwrap\wraps
# OpenWrap Shell 2.0.0.10
# Copyright Â© naughtyProd Limited 2009-2011
# Using D:\code\oss\openwrap\wraps\_cache\openwrap-2.0.0.86965964\bin-net35\OpenWrap.dll (2.0.0.1)

# OpenWrap Shell could not start.

Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.Fi
leNotFoundException: Could not load file or assembly 'Mono.Cecil, Version=0.9.4.0, Culture=neutral, PublicKeyToken=0738e
b9f132ed756' or one of its dependencies. The system cannot find the file specified.
File name: 'Mono.Cecil, Version=0.9.4.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
   at OpenWrap.Services.ServiceRegistry..ctor()
   at OpenWrap.Commands.Cli.ShellRunner.Main(IDictionary`2 env) in c:\src\openwrap\src\OpenWrap\Commands\Cli\ShellRunner
.cs:line 31

=== Pre-bind state information ===
LOG: User = isomorphism\xyz
LOG: DisplayName = Mono.Cecil, Version=0.9.4.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
 (Fully-specified)
LOG: Appbase = file:///C:/Users/xyz/AppData/Local/openwrap/
LOG: Initial PrivatePath = NULL
Calling assembly : OpenWrap, Version=2.0.0.21372, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like
 with Assembly.Load().
LOG: Using application configuration file: C:\Users\xyz\AppData\Local\openwrap\o.exe.Config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v2.0.50727\config\machine.config.
LOG: Post-policy reference: Mono.Cecil, Version=0.9.4.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
LOG: The same bind was seen before, and was failed with hr = 0x80070002.

   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttrib
utes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OpenWrap.BootstrapRunner.<>c__DisplayClass16.<LoadEntrypointCache>b__15(IDictionary`2 env)
   at OpenWrap.BootstrapRunner.ExecuteEntrypoint(KeyValuePair`2 entryPoint, IEnumerable`1 assemblies, IEnumerable`1 cons
umedArgs)
   at OpenWrap.BootstrapRunner.Run(String[] args)
```

Was trying to build the wrap to the system directory...

**Comment by drozzy** [comment]
This bug is confirmed. I get the same never-terminating behavior if I query nuget repo (which I had to add as "o add-remote myRepo http://blah...")
