### ISSUE TITLE
Reference not found by Resharper plugin when project in solution dir

### ISSUE THREAD

**Issue by simonlaroche** [OpenWrap/openwrap#309]
When a project is in a solution directory the resharper plugin does not find the assembly references, when I remove the solution directory, the plugin works fine.

Resharper 6.0
OpenWrap 2.0.2.97071696 (from the beta repo IIRC)

**Comment by serialseb** [comment]
Are there any exceptions or traces in the OpenWrap section of the output window?

## 

Seb

**Comment by simonlaroche** [comment]
Exception is only in the UICommand Plugin

OpenWrap Visual Studio Integration (2.0.0.1) starting.
Root location: C:\Users\slaroche\Projects\kaju-github\Simple.Testing
Loading packages...
Loading package C:\Users\slaroche\Projects\kaju-github\Simple.Testing\wraps_cache\openwrap-2.0.2.97071696
Loading package C:\Users\slaroche\Projects\kaju-github\Simple.Testing\wraps_cache\SharpZipLib-0.86.0
Loading package C:\Users\slaroche\Projects\kaju-github\Simple.Testing\wraps_cache\tdnet-framework-2.0.0.48555719
Loading package C:\Users\slaroche\Projects\kaju-github\Simple.Testing\wraps_cache\Mono.Cecil-0.9.4.1
Loading package C:\Users\slaroche\Projects\kaju-github\Simple.Testing\wraps_cache\openfilesystem-1.0.1.88267869
Solution plugins starting...
Starting plugin UICommandsPlugin.
Plugin initialization failed.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenWrap.VisualStudio.Hooks.UICommandsPlugin.Initialize() in c:\Users\slaroche\Projects\github\openrasta\openwrap\src\OpenWrap.VisualStudio.SolutionPlugins\Hooks\UICommands\UICommandsPlugin.cs:line 68
   at OpenWrap.VisualStudio.Hooks.UICommandsPlugin..ctor(ICommandRepository commands) in c:\Users\slaroche\Projects\github\openrasta\openwrap\src\OpenWrap.VisualStudio.SolutionPlugins\Hooks\UICommands\UICommandsPlugin.cs:line 27
   at OpenWrap.VisualStudio.Hooks.UICommandsPlugin..ctor() in c:\Users\slaroche\Projects\github\openrasta\openwrap\src\OpenWrap.VisualStudio.SolutionPlugins\Hooks\UICommands\UICommandsPlugin.cs:line 19
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipVisibilityChecks, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName)
   at OpenWrap.PackageManagement.Exporters.SolutionPlugin.Start() in c:\Users\slaroche\Projects\github\openrasta\openwrap\src\OpenWrap\PackageManagement\Exporters\SolutionPlugin.cs:line 30
   at OpenWrap.Commands.Core.StartSolutionPlugin.<>c__DisplayClass27.<LoadPlugin>b__25() in c:\Users\slaroche\Projects\github\openrasta\openwrap\src\OpenWrap.Commands\Core\StartSolutionPlugin.cs:line 126
   at OpenWrap.Commands.Core.StartSolutionPlugin.TryDo(Action action, Action`1 onError) in c:\Users\slaroche\Projects\github\openrasta\openwrap\src\OpenWrap.Commands\Core\StartSolutionPlugin.cs:line 150
Starting plugin AssemblyReferenceNotificationsPlugin.
Starting plugin ReSharperLoaderPlugin.
Resharper Plugin Manager: Loaded (99.99.266.5825).
ReSharper Project Reference Updater: Solution opened Simple
ReSharper Project Reference Updater: Changes detected, updating assembly references (35738073).
All solution plugins started.
ReSharper test runner starting.

**Comment by simonlaroche** [comment]
Just to make things clear, the plugin does not work for projects in a solution folder in the solution explorer not the actual solution directory.
