### ISSUE TITLE
InitializeOpenWrap task missing current directory

### ISSUE THREAD

**Issue by simonlaroche** [OpenWrap/openwrap#316]
The MSBuild Task InitializeOpenWrap is missing the CurrentDirectory parameter.

Version:  f/semver

An argument null exception is thrown if I build either from VS or the build-wrap command

Error   1   The "InitializeOpenWrap" task failed unexpectedly.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.DirectoryInfo..ctor(String path)
   at OpenFileSystem.IO.FileSystems.Local.Win32.Win32FileSystem.GetDirectory(String directoryPath) in c:\src\openfilesystem\src\OpenFileSystem\FileSystems\Local\Win32\Win32FileSystem.cs:line 10
   at OpenWrap.Build.BuildInitializer.Initialize(String projectFile, String currentDirectory) in c:\Users\slaroche\Projects\github\openrasta\openwrap\src\OpenWrap\Build\BuildInitializer.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.RuntimeMethodHandle.InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OpenWrap.Build.InitializeOpenWrap.Execute() in c:\Users\slaroche\Projects\github\openrasta\openwrap\src\OpenWrap.Build.Bootstrap\InitializeOpenWrap.cs:line 41
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask, Boolean& taskResult)   monorail.ow

**Comment by simonlaroche** [comment]
Seems to be fixed in f/tcbuild branch
