### ISSUE TITLE
Install throws unhandled exception if wraps.openwrap.org not accessible:

### ISSUE THREAD

**Issue by conficient** [OpenWrap/openwrap#91]
Scenario:
- first time install of OpenWrap using o.exe on Windows 7 x64 workstation.
- copied o.exe to local disk
- ran o.exe
- after "Downloading http://wraps.openwrap.org/bootstrap" the app threw unhandled exception (below).

Suggested fix: 
- would have expected not found exception to be handled gracefully (in this case the server not yet in existence) or if network not available

System.Reflection.TargetInvocationException was unhandled
  Message=An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.
  Source=System
  StackTrace:
       at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
       at System.Net.DownloadStringCompletedEventArgs.get_Result()
       at OpenWrap.Console.BootstrapRunner.NotifyProgressWebClient.DownloadStringCompleted(Object src, DownloadStringCompletedEventArgs e)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallbackInternal(_ThreadPoolWaitCallback tpWaitCallBack)
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback(Object state)
  InnerException: System.Net.WebException
       Message=The remote name could not be resolved: 'wraps.openwrap.org'
       Source=System
       StackTrace:
            at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
            at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
            at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
       InnerException:

**Comment by serialseb** [comment]
Not in the correct project. Re-added to openwrap-bootstrap.
