### ISSUE TITLE
Install throws unhandled exception if "wraps.openwrap.org" not resolved / accessible:

### ISSUE THREAD

**Issue by conficient** [OpenWrap/openwrap#92]
Installing OpenWrap for the first time, got an unhandled exception as part of the install:

System.Reflection.TargetInvocationException was unhandled
  Message=An exception occurred during the operation, making the result invalid.  Check InnerException for exception details.
  Source=System
  StackTrace:
       at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
       at System.Net.DownloadStringCompletedEventArgs.get_Result()
       at OpenWrap.Console.BootstrapRunner.NotifyProgressWebClient.DownloadStringCompleted(Object src, DownloadStringCompletedEventArgs e)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallbackInternal(_ThreadPoolWaitCallback tpWaitCallBack)
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback(Object state)
  InnerException: System.Net.WebException
       Message=The remote name could not be resolved: 'wraps.openwrap.org'
       Source=System
       StackTrace:
            at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
            at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
            at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
       InnerException: 

wraps.openwrap.org is not resolving. Would have expected OpenWrap to handle this and report.

**Comment by serialseb** [comment]
duplicate
