### ISSUE TITLE
404 on http://wraps.openwrap.org/bootstrap

### ISSUE THREAD

**Issue by jhollingworth** [OpenWrap/openwrap#93]
When I download the openwrap version from http://openwrap.org I get an exception when trying to get packages.

<pre>
OpenWrap packages not found. Attempting download.
Downloading http://wraps.openwrap.org/bootstrap [
Unhandled Exception: System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebExcept
ion: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at System.Net.DownloadStringCompletedEventArgs.get_Result()
   at OpenWrap.Console.BootstrapRunner.NotifyProgressWebClient.DownloadStringCompleted(Object src, DownloadStringCompletedEventArgs e)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallbackInternal(_ThreadPoolWaitCallback tpWaitCallBack)
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback(Object state)
</pre>

**Comment by serialseb** [comment]
Fixed
